import models from '.';
import db from '../db';
import config from '../config';
import logger from '../logger';

const obj = {
  categories: [
    {
      digital: '2:42:36',
      hours: 2,
      minutes: 42,
      name: 'Coding',
      percent: 100.0,
      seconds: 36,
      text: '2 hrs 42 mins',
      total_seconds: 9756.167683,
    },
  ],
  date: '2021-04-22',
  dependencies: [],
  editors: [
    {
      digital: '2:42:36',
      hours: 2,
      minutes: 42,
      name: 'VS Code',
      percent: 100.0,
      seconds: 36,
      text: '2 hrs 42 mins',
      total_seconds: 9756.167683,
    },
  ],
  grand_total: {
    digital: '2:42',
    hours: 2,
    minutes: 42,
    text: '2 hrs 42 mins',
    total_seconds: 9756.167683,
  },
  languages: [
    {
      digital: '2:13:50',
      hours: 2,
      minutes: 13,
      name: 'TypeScript',
      percent: 82.31,
      seconds: 50,
      text: '2 hrs 13 mins',
      total_seconds: 8030.052554,
    },
    {
      digital: '0:20:36',
      hours: 0,
      minutes: 20,
      name: 'Vue.js',
      percent: 12.68,
      seconds: 36,
      text: '20 mins',
      total_seconds: 1236.777322,
    },
    {
      digital: '0:08:04',
      hours: 0,
      minutes: 8,
      name: 'Markdown',
      percent: 4.96,
      seconds: 4,
      text: '8 mins',
      total_seconds: 484.024525,
    },
    {
      digital: '0:00:05',
      hours: 0,
      minutes: 0,
      name: 'JSON',
      percent: 0.05,
      seconds: 5,
      text: '5 secs',
      total_seconds: 5.313282,
    },
  ],
  machines: [
    {
      digital: '2:42:36',
      hours: 2,
      machine_name_id: 'd97ad69d-1fb5-48f1-a2b4-5f9aae9e1d87',
      minutes: 42,
      name: 'laptop-xfy',
      percent: 100.0,
      seconds: 36,
      text: '2 hrs 42 mins',
      total_seconds: 9756.167683,
    },
  ],
  operating_systems: [
    {
      digital: '2:42:36',
      hours: 2,
      minutes: 42,
      name: 'Windows',
      percent: 100.0,
      seconds: 36,
      text: '2 hrs 42 mins',
      total_seconds: 9756.167683,
    },
  ],
  projects: [
    {
      branches: [
        {
          decimal: '2.03',
          digital: '2:02:18',
          hours: 2,
          minutes: 2,
          name: 'master',
          percent: 100.0,
          seconds: 18,
          text: '2 hrs 2 mins',
          total_seconds: 7338.889281,
        },
      ],
      categories: [
        {
          decimal: '2.03',
          digital: '2:02:18',
          hours: 2,
          minutes: 2,
          name: 'Coding',
          percent: 100.0,
          seconds: 18,
          text: '2 hrs 2 mins',
          total_seconds: 7338.889281,
        },
      ],
      dependencies: [],
      editors: [
        {
          decimal: '2.03',
          digital: '2:02:18',
          hours: 2,
          minutes: 2,
          name: 'VS Code',
          percent: 100.0,
          seconds: 18,
          text: '2 hrs 2 mins',
          total_seconds: 7338.889281,
        },
      ],
      entities: [
        {
          decimal: '1.08',
          digital: '1:05:30',
          hours: 1,
          minutes: 5,
          name: 'C:/Git/gugu-mall/src/hook/home/homeLogic.ts',
          percent: 53.56,
          seconds: 30,
          text: '1 hr 5 mins',
          total_seconds: 3930.965738,
          type: 'file',
        },
        {
          decimal: '0.38',
          digital: '0:23:34',
          hours: 0,
          minutes: 23,
          name: 'C:/Git/gugu-mall/src/hook/category/categoryImgEffect.ts',
          percent: 19.28,
          seconds: 34,
          text: '23 mins',
          total_seconds: 1414.876252,
          type: 'file',
        },
        {
          decimal: '0.15',
          digital: '0:09:58',
          hours: 0,
          minutes: 9,
          name: 'C:/Git/gugu-mall/src/views/home/Home.vue',
          percent: 8.15,
          seconds: 58,
          text: '9 mins',
          total_seconds: 598.441303,
          type: 'file',
        },
        {
          decimal: '0.12',
          digital: '0:07:28',
          hours: 0,
          minutes: 7,
          name: 'C:/Git/gugu-mall/src/components/common/GoTop.vue',
          percent: 6.11,
          seconds: 28,
          text: '7 mins',
          total_seconds: 448.567116,
          type: 'file',
        },
        {
          decimal: '0.12',
          digital: '0:07:22',
          hours: 0,
          minutes: 7,
          name: 'C:/Git/gugu-mall/src/hook/common/recordScroll.ts',
          percent: 6.03,
          seconds: 22,
          text: '7 mins',
          total_seconds: 442.264179,
          type: 'file',
        },
        {
          decimal: '0.03',
          digital: '0:02:51',
          hours: 0,
          minutes: 2,
          name: 'C:/Git/gugu-mall/src/hook/category/categoryEffect.ts',
          percent: 2.34,
          seconds: 51,
          text: '2 mins',
          total_seconds: 171.838588,
          type: 'file',
        },
        {
          decimal: '0.03',
          digital: '0:02:13',
          hours: 0,
          minutes: 2,
          name: 'C:/Git/gugu-mall/src/views/category/Category.vue',
          percent: 1.82,
          seconds: 13,
          text: '2 mins',
          total_seconds: 133.691036,
          type: 'file',
        },
        {
          decimal: '0.03',
          digital: '0:02:07',
          hours: 0,
          minutes: 2,
          name: 'C:/Git/gugu-mall/README.md',
          percent: 1.74,
          seconds: 7,
          text: '2 mins',
          total_seconds: 127.433567,
          type: 'file',
        },
        {
          decimal: '0.00',
          digital: '0:00:34',
          hours: 0,
          minutes: 0,
          name: 'C:/Git/gugu-mall/src/views/detail/Detail.vue',
          percent: 0.47,
          seconds: 34,
          text: '34 secs',
          total_seconds: 34.641457,
          type: 'file',
        },
        {
          decimal: '0.00',
          digital: '0:00:17',
          hours: 0,
          minutes: 0,
          name: 'C:/Git/gugu-mall/src/views/home/children/Recommend.vue',
          percent: 0.24,
          seconds: 17,
          text: '17 secs',
          total_seconds: 17.840156,
          type: 'file',
        },
        {
          decimal: '0.00',
          digital: '0:00:11',
          hours: 0,
          minutes: 0,
          name: 'C:/Git/gugu-mall/src/hook/home/homeEffect.ts',
          percent: 0.15,
          seconds: 11,
          text: '11 secs',
          total_seconds: 11.009642,
          type: 'file',
        },
        {
          decimal: '0.00',
          digital: '0:00:03',
          hours: 0,
          minutes: 0,
          name: 'C:/Git/gugu-mall/src/views/home/children/WeekendRecommend.vue',
          percent: 0.05,
          seconds: 3,
          text: '3 secs',
          total_seconds: 3.596254,
          type: 'file',
        },
        {
          decimal: '0.00',
          digital: '0:00:02',
          hours: 0,
          minutes: 0,
          name: 'C:/Git/gugu-mall/src/hook/detail/detailImgEffect.ts',
          percent: 0.04,
          seconds: 2,
          text: '2 secs',
          total_seconds: 2.804574,
          type: 'file',
        },
        {
          decimal: '0.00',
          digital: '0:00:00',
          hours: 0,
          minutes: 0,
          name: 'C:/Git/gugu-mall/src/hook/category/categoryListEffect.ts',
          percent: 0.01,
          seconds: 0,
          text: '0 secs',
          total_seconds: 0.919419,
          type: 'file',
        },
      ],
      grand_total: {
        decimal: '2.03',
        digital: '2:02',
        hours: 2,
        minutes: 2,
        percent: 75.22,
        text: '2 hrs 2 mins',
        total_seconds: 7338.889281,
      },
      languages: [
        {
          decimal: '1.65',
          digital: '1:39:34',
          hours: 1,
          minutes: 39,
          name: 'TypeScript',
          percent: 81.41,
          seconds: 34,
          text: '1 hr 39 mins',
          total_seconds: 5974.678392,
        },
        {
          decimal: '0.33',
          digital: '0:20:36',
          hours: 0,
          minutes: 20,
          name: 'Vue.js',
          percent: 16.85,
          seconds: 36,
          text: '20 mins',
          total_seconds: 1236.777322,
        },
        {
          decimal: '0.03',
          digital: '0:02:07',
          hours: 0,
          minutes: 2,
          name: 'Markdown',
          percent: 1.74,
          seconds: 7,
          text: '2 mins',
          total_seconds: 127.433567,
        },
      ],
      machines: [
        {
          decimal: '2.03',
          digital: '2:02:18',
          hours: 2,
          machine_name_id: 'd97ad69d-1fb5-48f1-a2b4-5f9aae9e1d87',
          minutes: 2,
          name: 'laptop-xfy',
          percent: 100.0,
          seconds: 18,
          text: '2 hrs 2 mins',
          total_seconds: 7338.889281,
        },
      ],
      name: 'gugu-mall',
      operating_systems: [
        {
          decimal: '2.03',
          digital: '2:02:18',
          hours: 2,
          minutes: 2,
          name: 'Windows',
          percent: 100.0,
          seconds: 18,
          text: '2 hrs 2 mins',
          total_seconds: 7338.889281,
        },
      ],
    },
    {
      branches: [
        {
          decimal: '0.57',
          digital: '0:34:20',
          hours: 0,
          minutes: 34,
          name: 'master',
          percent: 100.0,
          seconds: 20,
          text: '34 mins',
          total_seconds: 2060.687444,
        },
      ],
      categories: [
        {
          decimal: '0.57',
          digital: '0:34:20',
          hours: 0,
          minutes: 34,
          name: 'Coding',
          percent: 100.0,
          seconds: 20,
          text: '34 mins',
          total_seconds: 2060.687444,
        },
      ],
      dependencies: [],
      editors: [
        {
          decimal: '0.57',
          digital: '0:34:20',
          hours: 0,
          minutes: 34,
          name: 'VS Code',
          percent: 100.0,
          seconds: 20,
          text: '34 mins',
          total_seconds: 2060.687444,
        },
      ],
      entities: [
        {
          decimal: '0.33',
          digital: '0:20:21',
          hours: 0,
          minutes: 20,
          name: 'C:/Git/gugumall-backend/src/server/routers/index.ts',
          percent: 59.27,
          seconds: 21,
          text: '20 mins',
          total_seconds: 1221.446209,
          type: 'file',
        },
        {
          decimal: '0.22',
          digital: '0:13:47',
          hours: 0,
          minutes: 13,
          name: 'C:/Git/gugumall-backend/src/server/app.ts',
          percent: 40.17,
          seconds: 47,
          text: '13 mins',
          total_seconds: 827.824768,
          type: 'file',
        },
        {
          decimal: '0.00',
          digital: '0:00:05',
          hours: 0,
          minutes: 0,
          name: 'C:/Git/gugumall-backend/src/crawler/data/recommend.json',
          percent: 0.26,
          seconds: 5,
          text: '5 secs',
          total_seconds: 5.313282,
          type: 'file',
        },
        {
          decimal: '0.00',
          digital: '0:00:03',
          hours: 0,
          minutes: 0,
          name: 'C:/Git/gugumall-backend/src/server/controllers/category/category.ts',
          percent: 0.15,
          seconds: 3,
          text: '3 secs',
          total_seconds: 3.15169,
          type: 'file',
        },
        {
          decimal: '0.00',
          digital: '0:00:02',
          hours: 0,
          minutes: 0,
          name: 'C:/Git/gugumall-backend/src/server/common/queryMongo.ts',
          percent: 0.14,
          seconds: 2,
          text: '2 secs',
          total_seconds: 2.951495,
          type: 'file',
        },
      ],
      grand_total: {
        decimal: '0.57',
        digital: '0:34',
        hours: 0,
        minutes: 34,
        percent: 21.12,
        text: '34 mins',
        total_seconds: 2060.687444,
      },
      languages: [
        {
          decimal: '0.57',
          digital: '0:34:15',
          hours: 0,
          minutes: 34,
          name: 'TypeScript',
          percent: 99.74,
          seconds: 15,
          text: '34 mins',
          total_seconds: 2055.374162,
        },
        {
          decimal: '0.00',
          digital: '0:00:05',
          hours: 0,
          minutes: 0,
          name: 'JSON',
          percent: 0.26,
          seconds: 5,
          text: '5 secs',
          total_seconds: 5.313282,
        },
      ],
      machines: [
        {
          decimal: '0.57',
          digital: '0:34:20',
          hours: 0,
          machine_name_id: 'd97ad69d-1fb5-48f1-a2b4-5f9aae9e1d87',
          minutes: 34,
          name: 'laptop-xfy',
          percent: 100.0,
          seconds: 20,
          text: '34 mins',
          total_seconds: 2060.687444,
        },
      ],
      name: 'gugumall-backend',
      operating_systems: [
        {
          decimal: '0.57',
          digital: '0:34:20',
          hours: 0,
          minutes: 34,
          name: 'Windows',
          percent: 100.0,
          seconds: 20,
          text: '34 mins',
          total_seconds: 2060.687444,
        },
      ],
    },
    {
      branches: [
        {
          decimal: '0.08',
          digital: '0:05:39',
          hours: 0,
          minutes: 5,
          name: 'master',
          percent: 100.0,
          seconds: 39,
          text: '5 mins',
          total_seconds: 339.320385,
        },
      ],
      categories: [
        {
          decimal: '0.08',
          digital: '0:05:39',
          hours: 0,
          minutes: 5,
          name: 'Coding',
          percent: 100.0,
          seconds: 39,
          text: '5 mins',
          total_seconds: 339.320385,
        },
      ],
      dependencies: [],
      editors: [
        {
          decimal: '0.08',
          digital: '0:05:39',
          hours: 0,
          minutes: 5,
          name: 'VS Code',
          percent: 100.0,
          seconds: 39,
          text: '5 mins',
          total_seconds: 339.320385,
        },
      ],
      entities: [
        {
          decimal: '0.08',
          digital: '0:05:39',
          hours: 0,
          minutes: 5,
          name: 'C:/Git/DefectingCat/README.md',
          percent: 100.0,
          seconds: 39,
          text: '5 mins',
          total_seconds: 339.320385,
          type: 'file',
        },
      ],
      grand_total: {
        decimal: '0.08',
        digital: '0:05',
        hours: 0,
        minutes: 5,
        percent: 3.48,
        text: '5 mins',
        total_seconds: 339.320385,
      },
      languages: [
        {
          decimal: '0.08',
          digital: '0:05:39',
          hours: 0,
          minutes: 5,
          name: 'Markdown',
          percent: 100.0,
          seconds: 39,
          text: '5 mins',
          total_seconds: 339.320385,
        },
      ],
      machines: [
        {
          decimal: '0.08',
          digital: '0:05:39',
          hours: 0,
          machine_name_id: 'd97ad69d-1fb5-48f1-a2b4-5f9aae9e1d87',
          minutes: 5,
          name: 'laptop-xfy',
          percent: 100.0,
          seconds: 39,
          text: '5 mins',
          total_seconds: 339.320385,
        },
      ],
      name: 'DefectingCat',
      operating_systems: [
        {
          decimal: '0.08',
          digital: '0:05:39',
          hours: 0,
          minutes: 5,
          name: 'Windows',
          percent: 100.0,
          seconds: 39,
          text: '5 mins',
          total_seconds: 339.320385,
        },
      ],
    },
    {
      branches: [
        {
          decimal: '0.00',
          digital: '0:00:17',
          hours: 0,
          minutes: 0,
          name: 'master',
          percent: 100.0,
          seconds: 17,
          text: '17 secs',
          total_seconds: 17.270573,
        },
      ],
      categories: [
        {
          decimal: '0.00',
          digital: '0:00:17',
          hours: 0,
          minutes: 0,
          name: 'Coding',
          percent: 100.0,
          seconds: 17,
          text: '17 secs',
          total_seconds: 17.270573,
        },
      ],
      dependencies: [],
      editors: [
        {
          decimal: '0.00',
          digital: '0:00:17',
          hours: 0,
          minutes: 0,
          name: 'VS Code',
          percent: 100.0,
          seconds: 17,
          text: '17 secs',
          total_seconds: 17.270573,
        },
      ],
      entities: [
        {
          decimal: '0.00',
          digital: '0:00:17',
          hours: 0,
          minutes: 0,
          name: 'C:/Git/blog/source/about/index.md',
          percent: 100.0,
          seconds: 17,
          text: '17 secs',
          total_seconds: 17.270573,
          type: 'file',
        },
      ],
      grand_total: {
        decimal: '0.00',
        digital: '0:00',
        hours: 0,
        minutes: 0,
        percent: 0.18,
        text: '0 secs',
        total_seconds: 17.270573,
      },
      languages: [
        {
          decimal: '0.00',
          digital: '0:00:17',
          hours: 0,
          minutes: 0,
          name: 'Markdown',
          percent: 100.0,
          seconds: 17,
          text: '17 secs',
          total_seconds: 17.270573,
        },
      ],
      machines: [
        {
          decimal: '0.00',
          digital: '0:00:17',
          hours: 0,
          machine_name_id: 'd97ad69d-1fb5-48f1-a2b4-5f9aae9e1d87',
          minutes: 0,
          name: 'laptop-xfy',
          percent: 100.0,
          seconds: 17,
          text: '17 secs',
          total_seconds: 17.270573,
        },
      ],
      name: 'blog',
      operating_systems: [
        {
          decimal: '0.00',
          digital: '0:00:17',
          hours: 0,
          minutes: 0,
          name: 'Windows',
          percent: 100.0,
          seconds: 17,
          text: '17 secs',
          total_seconds: 17.270573,
        },
      ],
    },
  ],
};

const connectDB = () => {
  console.log(db.connect(config.DB_HOST));
  logger.info('db connect');
};

const mongoTest = async () => {
  const res = await models.Waka.create(obj);
  console.log(res);
};

connectDB();
